# -*- coding: utf-8 -*-
"""web_scraping_II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZofXP-gqNYTzXdkAaewlkZHKwd82F3KQ

# Top 100 best movies of all time
 ## According to [empire online](https://www.empireonline.com/movies/features/best-movies-2/) as at December 2024.

 + Import Libaries
 + Performed Data extration through web sscraping using beautiful soup
 + Creat a text file from the scraped data.
"""

# import the required libaries

from bs4 import BeautifulSoup
import requests

try:
  response = requests.get("https://www.empireonline.com/movies/features/best-movies-2/")
  response.raise_for_status()
except RequestException as e:
  print(F"There was an issue with your request: {e}")
except HTTPError as e:
  print(F"HTTP error occured: {e}")

soup = BeautifulSoup(response.text, "html.parser")
top_100_movies = [movie.get_text().strip() for movie in soup.select("h2 strong")]
print(top_100_movies)

len(top_100_movies)

# reverse the top 100 movies of all times

movies_title = top_100_movies[::-1]
print(movies_title)

# save the movie title as a text file

with open("movies.txt", "w") as file:
  for movie in movies_title:
    file.write(f"{movie}\n")

